version: "2"
linters:
  enable:
    - gosec
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pmgledhill102/engineering-decisions
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
